
insert into users (first_name, last_name, email, password, phone_number) values ('Helli', 'Whittle', 'hwhittle0@loc.gov', '1MQFIJCxG', 69361722);
insert into users (first_name, last_name, email, password, phone_number) values ('Nappy', 'Engel', 'nengel1@flickr.com', 'sCzDBy', 40060817);
insert into users (first_name, last_name, email, password, phone_number) values ('Tildie', 'Hulance', 'thulance2@craigslist.org', 'mGWzZn', 12653970);
insert into users (first_name, last_name, email, password, phone_number) values ('Maribeth', 'Foresight', 'mforesight3@meetup.com', 'v4L4ze', 83355536);
insert into users (first_name, last_name, email, password, phone_number) values ('Shanon', 'Giacometti', 'sgiacometti4@marriott.com', '0iXcauISzZwE', 40153063);
insert into users (first_name, last_name, email, password, phone_number) values ('Alfredo', 'Blessed', 'ablessed5@about.me', 'mfpCm0dMFzPy', 24679872);
insert into users (first_name, last_name, email, password, phone_number) values ('Hildegaard', 'Kyle', 'hkyle6@google.es', '9nIsloi5PE', 86284164);
insert into users (first_name, last_name, email, password, phone_number) values ('Tripp', 'Denham', 'tdenham7@xing.com', 'DqikUvdgRV1o', 98550791);
insert into users (first_name, last_name, email, password, phone_number) values ('Theodor', 'Schultz', 'tschultz8@hatena.ne.jp', 'Sr07hI8wlxQx', 63575637);
insert into users (first_name, last_name, email, password, phone_number) values ('Dulcine', 'Wither', 'dwither9@ed.gov', 'e5NvAlRZzM', 68746215);
insert into users (first_name, last_name, email, password, phone_number) values ('Reinald', 'Musselwhite', 'rmusselwhitea@noaa.gov', 'iTA4trqTu5B', 95168974);
insert into users (first_name, last_name, email, password, phone_number) values ('Ray', 'Beden', 'rbedenb@earthlink.net', 'q0Ug6Fy', 52905483);
insert into users (first_name, last_name, email, password, phone_number) values ('Romeo', 'Gotmann', 'rgotmannc@umn.edu', 'YnWdlN', 75958898);
insert into users (first_name, last_name, email, password, phone_number) values ('Delano', 'Ansett', 'dansettd@dailymail.co.uk', 'Mmjt6AY4ryk', 30092511);
insert into users (first_name, last_name, email, password, phone_number) values ('Gideon', 'Loveitt', 'gloveitte@virginia.edu', 'dGYkgMAk0vr', 55933086);
insert into users (first_name, last_name, email, password, phone_number) values ('Artair', 'Hewertson', 'ahewertsonf@techcrunch.com', 'PpYSP2NntKs', 31177977);
insert into users (first_name, last_name, email, password, phone_number) values ('Bryon', 'Schieferstein', 'bschiefersteing@marriott.com', 'qoGUaSMsxUO', 20259371);
insert into users (first_name, last_name, email, password, phone_number) values ('Brooks', 'Denning', 'bdenningh@dmoz.org', 'zsfPjG3', 49651215);
insert into users (first_name, last_name, email, password, phone_number) values ('Stephani', 'Challenger', 'schallengeri@npr.org', 'lEU2Q2S', 84700238);
insert into users (first_name, last_name, email, password, phone_number) values ('Tabby', 'Gierardi', 'tgierardij@admin.ch', 'UNEckmhc', 69084457);
insert into users (first_name, last_name, email, password, phone_number) values ('Terrence', 'Lescop', 'tlescopk@wikimedia.org', 'bPNRFWfD3', 27771915);
insert into users (first_name, last_name, email, password, phone_number) values ('Dorine', 'Antram', 'dantraml@cdc.gov', 'lYwDf3iWjiiK', 15661170);
insert into users (first_name, last_name, email, password, phone_number) values ('Annabelle', 'Ert', 'aertm@mayoclinic.com', '8A3tl4', 35622464);
insert into users (first_name, last_name, email, password, phone_number) values ('Frannie', 'Mack', 'fmackn@about.com', 'kLgNuuisuT4', 87580470);
insert into users (first_name, last_name, email, password, phone_number) values ('Andre', 'Mottini', 'amottinio@theatlantic.com', 'pLnZJ1HSJrhm', 75587000);
insert into users (first_name, last_name, email, password, phone_number) values ('Zsazsa', 'Munks', 'zmunksp@nps.gov', 'MpeNQuP3Dhdk', 81850945);
insert into users (first_name, last_name, email, password, phone_number) values ('Nancey', 'MacMeekan', 'nmacmeekanq@archive.org', 'qDuqUWN8c', 38360695);
insert into users (first_name, last_name, email, password, phone_number) values ('Jacquenetta', 'Palomba', 'jpalombar@mapquest.com', 'zyhf2cmb', 69109260);
insert into users (first_name, last_name, email, password, phone_number) values ('Ernesta', 'Searl', 'esearls@google.co.uk', 'KB7hCzcvHSEw', 27004527);
insert into users (first_name, last_name, email, password, phone_number) values ('Reta', 'Briscoe', 'rbriscoet@harvard.edu', 'eXirOUU', 87324007);
insert into users (first_name, last_name, email, password, phone_number) values ('Miguela', 'Miner', 'mmineru@ocn.ne.jp', 'FRw4m9H4SJ', 78862290);
insert into users (first_name, last_name, email, password, phone_number) values ('Gradey', 'Pryn', 'gprynv@hatena.ne.jp', 'Cjq2s5MQd', 91382829);
insert into users (first_name, last_name, email, password, phone_number) values ('Isabelita', 'Broadis', 'ibroadisw@csmonitor.com', '33oDOjLrm', 22303387);
insert into users (first_name, last_name, email, password, phone_number) values ('Sophia', 'Bickle', 'sbicklex@tinyurl.com', '78UMsai0DHq', 89475375);
insert into users (first_name, last_name, email, password, phone_number) values ('Dyane', 'Sher', 'dshery@icq.com', '8CberhQK', 33569751);
insert into users (first_name, last_name, email, password, phone_number) values ('Dannel', 'Yannoni', 'dyannoniz@webnode.com', '2ksXbH4PR', 62561608);
insert into users (first_name, last_name, email, password, phone_number) values ('Emmerich', 'Canepe', 'ecanepe10@cnet.com', 'xUxPH32RCKx', 49307923);
insert into users (first_name, last_name, email, password, phone_number) values ('Trish', 'Snaddon', 'tsnaddon11@archive.org', 'li61zJ70K', 54014870);
insert into users (first_name, last_name, email, password, phone_number) values ('Irwinn', 'Aysh', 'iaysh12@dedecms.com', 'wkr7s3z5hDr', 14298659);
insert into users (first_name, last_name, email, password, phone_number) values ('Camel', 'Biford', 'cbiford13@ebay.co.uk', 'DMyot06sCbC8', 48337085);
insert into users (first_name, last_name, email, password, phone_number) values ('Hilary', 'Gulliman', 'hgulliman14@i2i.jp', 'Ue3wbg', 42296808);
insert into users (first_name, last_name, email, password, phone_number) values ('Andris', 'Rosenstock', 'arosenstock15@phpbb.com', 'vfl40w48XX', 42589998);
insert into users (first_name, last_name, email, password, phone_number) values ('Elvin', 'Carrane', 'ecarrane16@newyorker.com', 'KBXHG6', 17488854);
insert into users (first_name, last_name, email, password, phone_number) values ('Brett', 'Janku', 'bjanku17@etsy.com', 'OSONJIleh', 69402952);
insert into users (first_name, last_name, email, password, phone_number) values ('Raimundo', 'Broster', 'rbroster18@sitemeter.com', '8DPxGDeAL4Z', 36930813);
insert into users (first_name, last_name, email, password, phone_number) values ('Isis', 'Keitch', 'ikeitch19@smh.com.au', 'bAKYKJd', 68408709);
insert into users (first_name, last_name, email, password, phone_number) values ('Ewart', 'Bamell', 'ebamell1a@theglobeandmail.com', 'fg9EHXVHhyo7', 47220427);
insert into users (first_name, last_name, email, password, phone_number) values ('Perren', 'Shovel', 'pshovel1b@hp.com', 'xqJjK5', 53381059);
insert into users (first_name, last_name, email, password, phone_number) values ('Teena', 'Crace', 'tcrace1c@china.com.cn', 'rhoqkk0', 99143224);
insert into users (first_name, last_name, email, password, phone_number) values ('Massimiliano', 'Mellhuish', 'mmellhuish1d@illinois.edu', 'qsX3j4Ql6', 92786198);
insert into users (first_name, last_name, email, password, phone_number) values ('Shawna', 'McColl', 'smccoll1e@networkadvertising.org', 'Fkq5LnnjF6nc', 70185191);
insert into users (first_name, last_name, email, password, phone_number) values ('Lanae', 'Skillanders', 'lskillanders1f@whitehouse.gov', 'kvqzfbzfu', 54004094);
insert into users (first_name, last_name, email, password, phone_number) values ('Madalyn', 'Lunk', 'mlunk1g@gizmodo.com', 'iERNuXo1og', 46503059);
insert into users (first_name, last_name, email, password, phone_number) values ('Staffard', 'Berthot', 'sberthot1h@topsy.com', 'lFxGNHh', 58065087);
insert into users (first_name, last_name, email, password, phone_number) values ('Rozanna', 'Cundey', 'rcundey1i@nymag.com', 'GmJ5paF', 98451599);
insert into users (first_name, last_name, email, password, phone_number) values ('Theresita', 'Lathee', 'tlathee1j@hud.gov', 'HIAcNHD', 63834716);
insert into users (first_name, last_name, email, password, phone_number) values ('Josee', 'Bellworthy', 'jbellworthy1k@apache.org', 'oyUfUrrXynW', 87499656);
insert into users (first_name, last_name, email, password, phone_number) values ('Alexia', 'Daniele', 'adaniele1l@uol.com.br', 'VLQ5Tb', 97401309);
insert into users (first_name, last_name, email, password, phone_number) values ('Matti', 'Slatter', 'mslatter1m@auda.org.au', 'FG3V2L', 70153708);
insert into users (first_name, last_name, email, password, phone_number) values ('Marnia', 'Lockless', 'mlockless1n@cmu.edu', 'GC0cXqxoTH', 29117003);
insert into users (first_name, last_name, email, password, phone_number) values ('Corella', 'Mellmer', 'cmellmer1o@ca.gov', '3G6o2XI61if', 13629226);
insert into users (first_name, last_name, email, password, phone_number) values ('Chadwick', 'Helian', 'chelian1p@smugmug.com', 'cWvThJ', 67516730);
insert into users (first_name, last_name, email, password, phone_number) values ('Cory', 'Scotney', 'cscotney1q@netvibes.com', 'ZGrfFE', 27072910);
insert into users (first_name, last_name, email, password, phone_number) values ('Bunni', 'Toyne', 'btoyne1r@globo.com', '5iTBa6YebQtx', 71374122);
insert into users (first_name, last_name, email, password, phone_number) values ('Ody', 'Speirs', 'ospeirs1s@usa.gov', 'KcOaupUI', 35632693);
insert into users (first_name, last_name, email, password, phone_number) values ('Alleyn', 'McGarrity', 'amcgarrity1t@narod.ru', 'yyadR8GnDIJY', 95084262);
insert into users (first_name, last_name, email, password, phone_number) values ('Morey', 'Shipperbottom', 'mshipperbottom1u@yahoo.co.jp', 'dG4X796rT', 85807970);
insert into users (first_name, last_name, email, password, phone_number) values ('Amalea', 'Roja', 'aroja1v@un.org', 'xRF9T0Ac', 95379209);
insert into users (first_name, last_name, email, password, phone_number) values ('Dorrie', 'Manville', 'dmanville1w@stanford.edu', 'EfMV2gdM', 87805130);
insert into users (first_name, last_name, email, password, phone_number) values ('Carmita', 'McConnell', 'cmcconnell1x@hugedomains.com', 'vLLM2M', 39406070);
insert into users (first_name, last_name, email, password, phone_number) values ('Aile', 'Bilovsky', 'abilovsky1y@auda.org.au', 'FwmJoJvVwiD', 92247187);
insert into users (first_name, last_name, email, password, phone_number) values ('Ranique', 'Hoffner', 'rhoffner1z@quantcast.com', 'XzSg6l', 69518870);
insert into users (first_name, last_name, email, password, phone_number) values ('Else', 'Peeke-Vout', 'epeekevout20@unc.edu', 'Si9Lz2B', 24936132);
insert into users (first_name, last_name, email, password, phone_number) values ('Sharyl', 'Iacofo', 'siacofo21@java.com', '4mUsQq', 33470928);
insert into users (first_name, last_name, email, password, phone_number) values ('Sandye', 'Ansell', 'sansell22@addtoany.com', 'grNVXcn6TbLi', 83221497);
insert into users (first_name, last_name, email, password, phone_number) values ('Prisca', 'Rivett', 'privett23@scientificamerican.com', 'xjit9oeLx', 12435084);
insert into users (first_name, last_name, email, password, phone_number) values ('Fair', 'Emmison', 'femmison24@opensource.org', 'VKvQV7M7KNK', 72883136);
insert into users (first_name, last_name, email, password, phone_number) values ('Geoffrey', 'Purches', 'gpurches25@cnbc.com', '7NVbi6PDQ3', 18994049);
insert into users (first_name, last_name, email, password, phone_number) values ('Olympia', 'Dewing', 'odewing26@google.com.br', '5owddS', 42193092);
insert into users (first_name, last_name, email, password, phone_number) values ('Stearne', 'Screen', 'sscreen27@cdbaby.com', 'AjHbbovUp', 41815063);
insert into users (first_name, last_name, email, password, phone_number) values ('Nicolina', 'Fernao', 'nfernao28@wikimedia.org', 'c2HlBxCcX', 97956118);
insert into users (first_name, last_name, email, password, phone_number) values ('Mallorie', 'McGilleghole', 'mmcgilleghole29@dropbox.com', 'va7aqsHMGJ3h', 24001076);
insert into users (first_name, last_name, email, password, phone_number) values ('Arleta', 'Ellams', 'aellams2a@technorati.com', 'AUygSDGAnA', 14523882);
insert into users (first_name, last_name, email, password, phone_number) values ('Sigismondo', 'Braikenridge', 'sbraikenridge2b@digg.com', 'YfNWGhm9', 65562882);
insert into users (first_name, last_name, email, password, phone_number) values ('Natassia', 'Tortice', 'ntortice2c@exblog.jp', 'IQ4wZS', 19323081);
insert into users (first_name, last_name, email, password, phone_number) values ('Xenia', 'Mirfin', 'xmirfin2d@who.int', 'A07tibsjgeU', 62161143);
insert into users (first_name, last_name, email, password, phone_number) values ('Eimile', 'Prendergrast', 'eprendergrast2e@youtu.be', 'U9QgwMBDyRq', 84502500);
insert into users (first_name, last_name, email, password, phone_number) values ('Babb', 'Kitchenham', 'bkitchenham2f@ezinearticles.com', 'i9gIse', 75048574);
insert into users (first_name, last_name, email, password, phone_number) values ('Josselyn', 'Pim', 'jpim2g@is.gd', 'IF09TLum8XV', 13344442);
insert into users (first_name, last_name, email, password, phone_number) values ('Goddard', 'Littlejohns', 'glittlejohns2h@amazon.co.uk', 'WQCbwXJwW', 31327733);
insert into users (first_name, last_name, email, password, phone_number) values ('Hewett', 'Leney', 'hleney2i@yahoo.com', 'hYPn9ALndG', 51778520);
insert into users (first_name, last_name, email, password, phone_number) values ('Aleksandr', 'Sheach', 'asheach2j@soup.io', 'drxfWhqCcN5', 76882457);
insert into users (first_name, last_name, email, password, phone_number) values ('Elyse', 'Kalewe', 'ekalewe2k@networksolutions.com', '1Mex8bqr', 65881893);
insert into users (first_name, last_name, email, password, phone_number) values ('Annalee', 'Philippault', 'aphilippault2l@spotify.com', 'uWjtCfOI', 60651578);
insert into users (first_name, last_name, email, password, phone_number) values ('Tiffi', 'Kloser', 'tkloser2m@instagram.com', 'lUAr8FlKl', 53548963);
insert into users (first_name, last_name, email, password, phone_number) values ('Linoel', 'Wartonby', 'lwartonby2n@time.com', 'i7pcYbFN', 67988418);
insert into users (first_name, last_name, email, password, phone_number) values ('Lanie', 'Wickman', 'lwickman2o@narod.ru', 'DoIYyPJA7', 24033475);
insert into users (first_name, last_name, email, password, phone_number) values ('Levi', 'Whitnell', 'lwhitnell2p@yandex.ru', 'a4vqut50r0', 54910752);
insert into users (first_name, last_name, email, password, phone_number) values ('Bunnie', 'Skully', 'bskully2q@admin.ch', 'levWpn', 85212192);
insert into users (first_name, last_name, email, password, phone_number) values ('Shermy', 'Brody', 'sbrody2r@china.com.cn', 'ToqWplhb0kE', 72982149);

UPDATE users SET password = '0dd3e512642c97ca3f747f9a76e374fbda73f9292823c0313be9d78add7cdd8f72235af0c553dd26797e78e1854edee0ae002f8aba074b066dfce1af114e32f8';


INSERT INTO cuisines (name) VALUES ('Japanese');
INSERT INTO cuisines (name) VALUES ('Korean');
INSERT INTO cuisines (name) VALUES ('Malay');
INSERT INTO cuisines (name) VALUES ('Chinese');
INSERT INTO cuisines (name) VALUES ('Spanish/ Mexican');
INSERT INTO cuisines (name) VALUES ('Western');
INSERT INTO cuisines (name) VALUES ('Italian');
INSERT INTO cuisines (name) VALUES ('Indian');
INSERT INTO cuisines (name) VALUES ('Thai');



insert into user_friends (user_id, friend_id) values (1, 2);
insert into user_friends (user_id, friend_id) values (1, 44);
insert into user_friends (user_id, friend_id) values (1, 25);
insert into user_friends (user_id, friend_id) values (1, 39);
insert into user_friends (user_id, friend_id) values (1, 32);
insert into user_friends (user_id, friend_id) values (1, 34);
insert into user_friends (user_id, friend_id) values (1, 40);
insert into user_friends (user_id, friend_id) values (1, 20);
insert into user_friends (user_id, friend_id) values (2, 44);
insert into user_friends (user_id, friend_id) values (2, 13);
insert into user_friends (user_id, friend_id) values (2, 39);
insert into user_friends (user_id, friend_id) values (2, 41);
insert into user_friends (user_id, friend_id) values (2, 7);
insert into user_friends (user_id, friend_id) values (2, 42);
insert into user_friends (user_id, friend_id) values (2, 22);
insert into user_friends (user_id, friend_id) values (2, 11);
insert into user_friends (user_id, friend_id) values (2, 50);
insert into user_friends (user_id, friend_id) values (2, 43);
insert into user_friends (user_id, friend_id) values (3, 19);
insert into user_friends (user_id, friend_id) values (3, 22);
insert into user_friends (user_id, friend_id) values (3, 4);
insert into user_friends (user_id, friend_id) values (3, 37);
insert into user_friends (user_id, friend_id) values (3, 14);
insert into user_friends (user_id, friend_id) values (3, 44);
insert into user_friends (user_id, friend_id) values (3, 36);
insert into user_friends (user_id, friend_id) values (3, 39);
insert into user_friends (user_id, friend_id) values (4, 13);
insert into user_friends (user_id, friend_id) values (4, 29);
insert into user_friends (user_id, friend_id) values (4, 18);
insert into user_friends (user_id, friend_id) values (4, 2);
insert into user_friends (user_id, friend_id) values (4, 14);
insert into user_friends (user_id, friend_id) values (4, 33);
insert into user_friends (user_id, friend_id) values (4, 32);
insert into user_friends (user_id, friend_id) values (4, 28);
insert into user_friends (user_id, friend_id) values (4, 15);
insert into user_friends (user_id, friend_id) values (4, 50);
insert into user_friends (user_id, friend_id) values (4, 8);
insert into user_friends (user_id, friend_id) values (4, 35);
insert into user_friends (user_id, friend_id) values (4, 25);
insert into user_friends (user_id, friend_id) values (5, 50);
insert into user_friends (user_id, friend_id) values (5, 39);
insert into user_friends (user_id, friend_id) values (5, 9);
insert into user_friends (user_id, friend_id) values (5, 17);
insert into user_friends (user_id, friend_id) values (5, 14);
insert into user_friends (user_id, friend_id) values (6, 27);
insert into user_friends (user_id, friend_id) values (6, 46);
insert into user_friends (user_id, friend_id) values (6, 23);
insert into user_friends (user_id, friend_id) values (6, 20);
insert into user_friends (user_id, friend_id) values (6, 36);
insert into user_friends (user_id, friend_id) values (7, 32);
insert into user_friends (user_id, friend_id) values (7, 23);
insert into user_friends (user_id, friend_id) values (7, 22);
insert into user_friends (user_id, friend_id) values (7, 8);
insert into user_friends (user_id, friend_id) values (7, 37);
insert into user_friends (user_id, friend_id) values (7, 36);
insert into user_friends (user_id, friend_id) values (7, 29);
insert into user_friends (user_id, friend_id) values (7, 14);
insert into user_friends (user_id, friend_id) values (7, 28);
insert into user_friends (user_id, friend_id) values (7, 26);
insert into user_friends (user_id, friend_id) values (7, 3);
insert into user_friends (user_id, friend_id) values (7, 9);
insert into user_friends (user_id, friend_id) values (8, 14);
insert into user_friends (user_id, friend_id) values (8, 11);
insert into user_friends (user_id, friend_id) values (8, 42);
insert into user_friends (user_id, friend_id) values (8, 30);
insert into user_friends (user_id, friend_id) values (8, 20);
insert into user_friends (user_id, friend_id) values (8, 34);
insert into user_friends (user_id, friend_id) values (8, 25);
insert into user_friends (user_id, friend_id) values (8, 7);
insert into user_friends (user_id, friend_id) values (9, 24);
insert into user_friends (user_id, friend_id) values (9, 46);
insert into user_friends (user_id, friend_id) values (9, 32);
insert into user_friends (user_id, friend_id) values (9, 15);
insert into user_friends (user_id, friend_id) values (10, 43);
insert into user_friends (user_id, friend_id) values (10, 38);
insert into user_friends (user_id, friend_id) values (10, 44);
insert into user_friends (user_id, friend_id) values (10, 15);
insert into user_friends (user_id, friend_id) values (10, 17);
insert into user_friends (user_id, friend_id) values (10, 30);
insert into user_friends (user_id, friend_id) values (10, 1);
insert into user_friends (user_id, friend_id) values (10, 50);
insert into user_friends (user_id, friend_id) values (10, 46);
insert into user_friends (user_id, friend_id) values (11, 18);
insert into user_friends (user_id, friend_id) values (11, 33);
insert into user_friends (user_id, friend_id) values (11, 15);
insert into user_friends (user_id, friend_id) values (11, 13);
insert into user_friends (user_id, friend_id) values (11, 16);
insert into user_friends (user_id, friend_id) values (11, 21);
insert into user_friends (user_id, friend_id) values (11, 12);
insert into user_friends (user_id, friend_id) values (11, 20);
insert into user_friends (user_id, friend_id) values (12, 27);
insert into user_friends (user_id, friend_id) values (12, 31);
insert into user_friends (user_id, friend_id) values (12, 24);
insert into user_friends (user_id, friend_id) values (12, 22);
insert into user_friends (user_id, friend_id) values (12, 33);
insert into user_friends (user_id, friend_id) values (13, 39);
insert into user_friends (user_id, friend_id) values (13, 40);
insert into user_friends (user_id, friend_id) values (13, 27);
insert into user_friends (user_id, friend_id) values (13, 12);
insert into user_friends (user_id, friend_id) values (13, 28);
insert into user_friends (user_id, friend_id) values (13, 41);
insert into user_friends (user_id, friend_id) values (13, 5);
insert into user_friends (user_id, friend_id) values (13, 15);
insert into user_friends (user_id, friend_id) values (13, 43);
insert into user_friends (user_id, friend_id) values (13, 30);
insert into user_friends (user_id, friend_id) values (13, 16);
insert into user_friends (user_id, friend_id) values (13, 44);
insert into user_friends (user_id, friend_id) values (13, 14);
insert into user_friends (user_id, friend_id) values (13, 21);
insert into user_friends (user_id, friend_id) values (14, 40);
insert into user_friends (user_id, friend_id) values (14, 21);
insert into user_friends (user_id, friend_id) values (14, 45);
insert into user_friends (user_id, friend_id) values (14, 16);
insert into user_friends (user_id, friend_id) values (14, 18);
insert into user_friends (user_id, friend_id) values (14, 29);
insert into user_friends (user_id, friend_id) values (14, 24);
insert into user_friends (user_id, friend_id) values (14, 42);
insert into user_friends (user_id, friend_id) values (14, 37);
insert into user_friends (user_id, friend_id) values (14, 29);
insert into user_friends (user_id, friend_id) values (14, 25);
insert into user_friends (user_id, friend_id) values (14, 3);
insert into user_friends (user_id, friend_id) values (14, 33);
insert into user_friends (user_id, friend_id) values (14, 1);
insert into user_friends (user_id, friend_id) values (14, 27);
insert into user_friends (user_id, friend_id) values (14, 50);
insert into user_friends (user_id, friend_id) values (14, 8);
insert into user_friends (user_id, friend_id) values (14, 44);
insert into user_friends (user_id, friend_id) values (14, 7);
insert into user_friends (user_id, friend_id) values (14, 19);
insert into user_friends (user_id, friend_id) values (15, 26);
insert into user_friends (user_id, friend_id) values (15, 32);
insert into user_friends (user_id, friend_id) values (15, 39);
insert into user_friends (user_id, friend_id) values (15, 50);
insert into user_friends (user_id, friend_id) values (16, 30);
insert into user_friends (user_id, friend_id) values (16, 38);
insert into user_friends (user_id, friend_id) values (16, 45);
insert into user_friends (user_id, friend_id) values (16, 49);
insert into user_friends (user_id, friend_id) values (16, 28);
insert into user_friends (user_id, friend_id) values (16, 17);
insert into user_friends (user_id, friend_id) values (17, 20);
insert into user_friends (user_id, friend_id) values (17, 40);
insert into user_friends (user_id, friend_id) values (17, 19);
insert into user_friends (user_id, friend_id) values (17, 18);
insert into user_friends (user_id, friend_id) values (17, 5);
insert into user_friends (user_id, friend_id) values (17, 50);
insert into user_friends (user_id, friend_id) values (17, 27);
insert into user_friends (user_id, friend_id) values (18, 27);
insert into user_friends (user_id, friend_id) values (18, 47);
insert into user_friends (user_id, friend_id) values (18, 28);
insert into user_friends (user_id, friend_id) values (18, 33);
insert into user_friends (user_id, friend_id) values (18, 38);
insert into user_friends (user_id, friend_id) values (18, 41);
insert into user_friends (user_id, friend_id) values (18, 25);
insert into user_friends (user_id, friend_id) values (19, 32);
insert into user_friends (user_id, friend_id) values (19, 40);
insert into user_friends (user_id, friend_id) values (19, 22);
insert into user_friends (user_id, friend_id) values (19, 28);
insert into user_friends (user_id, friend_id) values (19, 47);
insert into user_friends (user_id, friend_id) values (19, 49);
insert into user_friends (user_id, friend_id) values (19, 9);
insert into user_friends (user_id, friend_id) values (19, 34);
insert into user_friends (user_id, friend_id) values (19, 50);
insert into user_friends (user_id, friend_id) values (20, 43);
insert into user_friends (user_id, friend_id) values (20, 50);
insert into user_friends (user_id, friend_id) values (20, 33);
insert into user_friends (user_id, friend_id) values (20, 21);
insert into user_friends (user_id, friend_id) values (20, 47);
insert into user_friends (user_id, friend_id) values (20, 4);
insert into user_friends (user_id, friend_id) values (20, 34);
insert into user_friends (user_id, friend_id) values (20, 49);
insert into user_friends (user_id, friend_id) values (20, 29);
insert into user_friends (user_id, friend_id) values (20, 42);
insert into user_friends (user_id, friend_id) values (21, 48);
insert into user_friends (user_id, friend_id) values (21, 41);
insert into user_friends (user_id, friend_id) values (21, 22);
insert into user_friends (user_id, friend_id) values (21, 45);
insert into user_friends (user_id, friend_id) values (21, 3);
insert into user_friends (user_id, friend_id) values (21, 46);
insert into user_friends (user_id, friend_id) values (21, 39);
insert into user_friends (user_id, friend_id) values (21, 31);
insert into user_friends (user_id, friend_id) values (21, 50);
insert into user_friends (user_id, friend_id) values (21, 44);
insert into user_friends (user_id, friend_id) values (22, 28);
insert into user_friends (user_id, friend_id) values (22, 38);
insert into user_friends (user_id, friend_id) values (22, 37);
insert into user_friends (user_id, friend_id) values (22, 42);
insert into user_friends (user_id, friend_id) values (22, 39);
insert into user_friends (user_id, friend_id) values (22, 27);
insert into user_friends (user_id, friend_id) values (22, 25);
insert into user_friends (user_id, friend_id) values (22, 45);
insert into user_friends (user_id, friend_id) values (22, 48);
insert into user_friends (user_id, friend_id) values (22, 26);
insert into user_friends (user_id, friend_id) values (23, 9);
insert into user_friends (user_id, friend_id) values (23, 15);
insert into user_friends (user_id, friend_id) values (23, 19);
insert into user_friends (user_id, friend_id) values (23, 13);
insert into user_friends (user_id, friend_id) values (23, 20);
insert into user_friends (user_id, friend_id) values (23, 8);
insert into user_friends (user_id, friend_id) values (23, 16);
insert into user_friends (user_id, friend_id) values (23, 22);
insert into user_friends (user_id, friend_id) values (23, 8);
insert into user_friends (user_id, friend_id) values (23, 14);
insert into user_friends (user_id, friend_id) values (24, 21);
insert into user_friends (user_id, friend_id) values (24, 1);
insert into user_friends (user_id, friend_id) values (24, 10);
insert into user_friends (user_id, friend_id) values (24, 12);
insert into user_friends (user_id, friend_id) values (24, 14);
insert into user_friends (user_id, friend_id) values (24, 2);
insert into user_friends (user_id, friend_id) values (24, 23);
insert into user_friends (user_id, friend_id) values (24, 44);
insert into user_friends (user_id, friend_id) values (24, 7);
insert into user_friends (user_id, friend_id) values (24, 16);
insert into user_friends (user_id, friend_id) values (25, 15);
insert into user_friends (user_id, friend_id) values (25, 3);
insert into user_friends (user_id, friend_id) values (25, 19);
insert into user_friends (user_id, friend_id) values (25, 34);
insert into user_friends (user_id, friend_id) values (25, 2);
insert into user_friends (user_id, friend_id) values (25, 21);
insert into user_friends (user_id, friend_id) values (26, 22);
insert into user_friends (user_id, friend_id) values (26, 9);
insert into user_friends (user_id, friend_id) values (26, 8);
insert into user_friends (user_id, friend_id) values (26, 5);
insert into user_friends (user_id, friend_id) values (26, 19);
insert into user_friends (user_id, friend_id) values (26, 24);
insert into user_friends (user_id, friend_id) values (26, 4);
insert into user_friends (user_id, friend_id) values (27, 4);
insert into user_friends (user_id, friend_id) values (27, 18);
insert into user_friends (user_id, friend_id) values (27, 8);
insert into user_friends (user_id, friend_id) values (27, 12);
insert into user_friends (user_id, friend_id) values (27, 10);
insert into user_friends (user_id, friend_id) values (28, 46);
insert into user_friends (user_id, friend_id) values (28, 33);
insert into user_friends (user_id, friend_id) values (28, 38);
insert into user_friends (user_id, friend_id) values (28, 37);
insert into user_friends (user_id, friend_id) values (28, 45);
insert into user_friends (user_id, friend_id) values (29, 4);
insert into user_friends (user_id, friend_id) values (29, 15);
insert into user_friends (user_id, friend_id) values (29, 26);
insert into user_friends (user_id, friend_id) values (29, 24);
insert into user_friends (user_id, friend_id) values (29, 10);
insert into user_friends (user_id, friend_id) values (30, 27);
insert into user_friends (user_id, friend_id) values (30, 2);
insert into user_friends (user_id, friend_id) values (30, 21);
insert into user_friends (user_id, friend_id) values (30, 14);
insert into user_friends (user_id, friend_id) values (30, 8);
insert into user_friends (user_id, friend_id) values (30, 25);
insert into user_friends (user_id, friend_id) values (30, 8);
insert into user_friends (user_id, friend_id) values (30, 24);
insert into user_friends (user_id, friend_id) values (31, 30);
insert into user_friends (user_id, friend_id) values (31, 18);
insert into user_friends (user_id, friend_id) values (31, 25);
insert into user_friends (user_id, friend_id) values (31, 1);
insert into user_friends (user_id, friend_id) values (32, 11);
insert into user_friends (user_id, friend_id) values (32, 5);
insert into user_friends (user_id, friend_id) values (32, 17);
insert into user_friends (user_id, friend_id) values (32, 45);
insert into user_friends (user_id, friend_id) values (32, 22);
insert into user_friends (user_id, friend_id) values (32, 6);
insert into user_friends (user_id, friend_id) values (33, 8);
insert into user_friends (user_id, friend_id) values (33, 31);
insert into user_friends (user_id, friend_id) values (33, 7);
insert into user_friends (user_id, friend_id) values (33, 10);
insert into user_friends (user_id, friend_id) values (33, 15);
insert into user_friends (user_id, friend_id) values (33, 32);
insert into user_friends (user_id, friend_id) values (33, 30);
insert into user_friends (user_id, friend_id) values (33, 29);
insert into user_friends (user_id, friend_id) values (33, 45);
insert into user_friends (user_id, friend_id) values (33, 2);
insert into user_friends (user_id, friend_id) values (34, 19);
insert into user_friends (user_id, friend_id) values (34, 23);
insert into user_friends (user_id, friend_id) values (34, 21);
insert into user_friends (user_id, friend_id) values (34, 18);
insert into user_friends (user_id, friend_id) values (34, 29);
insert into user_friends (user_id, friend_id) values (34, 43);
insert into user_friends (user_id, friend_id) values (34, 6);
insert into user_friends (user_id, friend_id) values (34, 35);
insert into user_friends (user_id, friend_id) values (34, 17);
insert into user_friends (user_id, friend_id) values (34, 27);
insert into user_friends (user_id, friend_id) values (35, 25);
insert into user_friends (user_id, friend_id) values (35, 8);
insert into user_friends (user_id, friend_id) values (35, 33);
insert into user_friends (user_id, friend_id) values (35, 31);
insert into user_friends (user_id, friend_id) values (35, 29);
insert into user_friends (user_id, friend_id) values (35, 3);
insert into user_friends (user_id, friend_id) values (35, 12);
insert into user_friends (user_id, friend_id) values (35, 10);




insert into user_preferences (user_id, cuisine_id) values (1, 1);
insert into user_preferences (user_id, cuisine_id) values (1, 5);
insert into user_preferences (user_id, cuisine_id) values (1, 6);
insert into user_preferences (user_id, cuisine_id) values (2, 3);
insert into user_preferences (user_id, cuisine_id) values (2, 4);
insert into user_preferences (user_id, cuisine_id) values (2, 9);
insert into user_preferences (user_id, cuisine_id) values (3, 3);
insert into user_preferences (user_id, cuisine_id) values (3, 7);
insert into user_preferences (user_id, cuisine_id) values (3, 4);
insert into user_preferences (user_id, cuisine_id) values (4, 4);
insert into user_preferences (user_id, cuisine_id) values (4, 3);
insert into user_preferences (user_id, cuisine_id) values (4, 9);
insert into user_preferences (user_id, cuisine_id) values (4, 6);
insert into user_preferences (user_id, cuisine_id) values (4, 7);
insert into user_preferences (user_id, cuisine_id) values (5, 3);
insert into user_preferences (user_id, cuisine_id) values (5, 5);
insert into user_preferences (user_id, cuisine_id) values (5, 6);
insert into user_preferences (user_id, cuisine_id) values (5, 1);
insert into user_preferences (user_id, cuisine_id) values (5, 8);
insert into user_preferences (user_id, cuisine_id) values (6, 2);
insert into user_preferences (user_id, cuisine_id) values (6, 5);
insert into user_preferences (user_id, cuisine_id) values (6, 3);
insert into user_preferences (user_id, cuisine_id) values (6, 6);
insert into user_preferences (user_id, cuisine_id) values (7, 5);
insert into user_preferences (user_id, cuisine_id) values (7, 1);
insert into user_preferences (user_id, cuisine_id) values (7, 2);
insert into user_preferences (user_id, cuisine_id) values (7, 7);
insert into user_preferences (user_id, cuisine_id) values (8, 3);
insert into user_preferences (user_id, cuisine_id) values (8, 3);
insert into user_preferences (user_id, cuisine_id) values (8, 8);
insert into user_preferences (user_id, cuisine_id) values (8, 5);
insert into user_preferences (user_id, cuisine_id) values (8, 2);
insert into user_preferences (user_id, cuisine_id) values (9, 1);
insert into user_preferences (user_id, cuisine_id) values (9, 4);
insert into user_preferences (user_id, cuisine_id) values (9, 6);
insert into user_preferences (user_id, cuisine_id) values (10, 4);
insert into user_preferences (user_id, cuisine_id) values (10, 7);
insert into user_preferences (user_id, cuisine_id) values (10, 6);
insert into user_preferences (user_id, cuisine_id) values (11, 2);
insert into user_preferences (user_id, cuisine_id) values (11, 9);
insert into user_preferences (user_id, cuisine_id) values (11, 4);
insert into user_preferences (user_id, cuisine_id) values (11, 3);
insert into user_preferences (user_id, cuisine_id) values (11, 1);
insert into user_preferences (user_id, cuisine_id) values (12, 5);
insert into user_preferences (user_id, cuisine_id) values (12, 3);
insert into user_preferences (user_id, cuisine_id) values (12, 2);
insert into user_preferences (user_id, cuisine_id) values (12, 1);
insert into user_preferences (user_id, cuisine_id) values (12, 6);
insert into user_preferences (user_id, cuisine_id) values (13, 7);
insert into user_preferences (user_id, cuisine_id) values (13, 8);
insert into user_preferences (user_id, cuisine_id) values (13, 3);
insert into user_preferences (user_id, cuisine_id) values (13, 2);
insert into user_preferences (user_id, cuisine_id) values (14, 4);
insert into user_preferences (user_id, cuisine_id) values (14, 5);
insert into user_preferences (user_id, cuisine_id) values (14, 6);
insert into user_preferences (user_id, cuisine_id) values (14, 8);
insert into user_preferences (user_id, cuisine_id) values (15, 2);
insert into user_preferences (user_id, cuisine_id) values (15, 3);
insert into user_preferences (user_id, cuisine_id) values (15, 1);
insert into user_preferences (user_id, cuisine_id) values (15, 5);
insert into user_preferences (user_id, cuisine_id) values (16, 9);
insert into user_preferences (user_id, cuisine_id) values (16, 8);
insert into user_preferences (user_id, cuisine_id) values (16, 1);
insert into user_preferences (user_id, cuisine_id) values (16, 2);
insert into user_preferences (user_id, cuisine_id) values (16, 3);
insert into user_preferences (user_id, cuisine_id) values (17, 2);
insert into user_preferences (user_id, cuisine_id) values (17, 4);
insert into user_preferences (user_id, cuisine_id) values (17, 7);
insert into user_preferences (user_id, cuisine_id) values (17, 3);
insert into user_preferences (user_id, cuisine_id) values (17, 1);
insert into user_preferences (user_id, cuisine_id) values (18, 1);
insert into user_preferences (user_id, cuisine_id) values (18, 3);
insert into user_preferences (user_id, cuisine_id) values (18, 6);
insert into user_preferences (user_id, cuisine_id) values (19, 9);
insert into user_preferences (user_id, cuisine_id) values (19, 2);
insert into user_preferences (user_id, cuisine_id) values (19, 6);
insert into user_preferences (user_id, cuisine_id) values (20, 8);
insert into user_preferences (user_id, cuisine_id) values (20, 6);
insert into user_preferences (user_id, cuisine_id) values (20, 1);
insert into user_preferences (user_id, cuisine_id) values (20, 5);
insert into user_preferences (user_id, cuisine_id) values (20, 4);
insert into user_preferences (user_id, cuisine_id) values (21, 8);
insert into user_preferences (user_id, cuisine_id) values (21, 9);
insert into user_preferences (user_id, cuisine_id) values (21, 2);
insert into user_preferences (user_id, cuisine_id) values (21, 7);
insert into user_preferences (user_id, cuisine_id) values (21, 5);
insert into user_preferences (user_id, cuisine_id) values (22, 3);
insert into user_preferences (user_id, cuisine_id) values (22, 1);
insert into user_preferences (user_id, cuisine_id) values (22, 6);
insert into user_preferences (user_id, cuisine_id) values (22, 7);
insert into user_preferences (user_id, cuisine_id) values (22, 2);
insert into user_preferences (user_id, cuisine_id) values (23, 6);
insert into user_preferences (user_id, cuisine_id) values (23, 4);
insert into user_preferences (user_id, cuisine_id) values (23, 2);
insert into user_preferences (user_id, cuisine_id) values (23, 1);
insert into user_preferences (user_id, cuisine_id) values (24, 2);
insert into user_preferences (user_id, cuisine_id) values (24, 1);
insert into user_preferences (user_id, cuisine_id) values (24, 3);
insert into user_preferences (user_id, cuisine_id) values (24, 8);
insert into user_preferences (user_id, cuisine_id) values (25, 9);
insert into user_preferences (user_id, cuisine_id) values (25, 8);
insert into user_preferences (user_id, cuisine_id) values (25, 4);
insert into user_preferences (user_id, cuisine_id) values (25, 6);
insert into user_preferences (user_id, cuisine_id) values (26, 3);
insert into user_preferences (user_id, cuisine_id) values (26, 2);
insert into user_preferences (user_id, cuisine_id) values (26, 5);
insert into user_preferences (user_id, cuisine_id) values (26, 6);
insert into user_preferences (user_id, cuisine_id) values (27, 7);
insert into user_preferences (user_id, cuisine_id) values (27, 2);
insert into user_preferences (user_id, cuisine_id) values (27, 4);
insert into user_preferences (user_id, cuisine_id) values (27, 5);
insert into user_preferences (user_id, cuisine_id) values (27, 3);
insert into user_preferences (user_id, cuisine_id) values (28, 5);
insert into user_preferences (user_id, cuisine_id) values (28, 1);
insert into user_preferences (user_id, cuisine_id) values (28, 3);
insert into user_preferences (user_id, cuisine_id) values (28, 8);
insert into user_preferences (user_id, cuisine_id) values (29, 1);
insert into user_preferences (user_id, cuisine_id) values (29, 5);
insert into user_preferences (user_id, cuisine_id) values (29, 2);
insert into user_preferences (user_id, cuisine_id) values (29, 3);
insert into user_preferences (user_id, cuisine_id) values (30, 4);
insert into user_preferences (user_id, cuisine_id) values (30, 6);
insert into user_preferences (user_id, cuisine_id) values (30, 8);
insert into user_preferences (user_id, cuisine_id) values (30, 7);
insert into user_preferences (user_id, cuisine_id) values (31, 4);
insert into user_preferences (user_id, cuisine_id) values (31, 1);
insert into user_preferences (user_id, cuisine_id) values (31, 2);
insert into user_preferences (user_id, cuisine_id) values (32, 3);
insert into user_preferences (user_id, cuisine_id) values (32, 8);
insert into user_preferences (user_id, cuisine_id) values (32, 1);
insert into user_preferences (user_id, cuisine_id) values (33, 6);
insert into user_preferences (user_id, cuisine_id) values (33, 3);
insert into user_preferences (user_id, cuisine_id) values (33, 4);
insert into user_preferences (user_id, cuisine_id) values (34, 8);
insert into user_preferences (user_id, cuisine_id) values (34, 2);
insert into user_preferences (user_id, cuisine_id) values (34, 5);
insert into user_preferences (user_id, cuisine_id) values (34, 1);
insert into user_preferences (user_id, cuisine_id) values (34, 6);
insert into user_preferences (user_id, cuisine_id) values (35, 1);
insert into user_preferences (user_id, cuisine_id) values (35, 8);
insert into user_preferences (user_id, cuisine_id) values (35, 5);
insert into user_preferences (user_id, cuisine_id) values (35, 7);
insert into user_preferences (user_id, cuisine_id) values (36, 3);
insert into user_preferences (user_id, cuisine_id) values (36, 9);
insert into user_preferences (user_id, cuisine_id) values (36, 5);
insert into user_preferences (user_id, cuisine_id) values (36, 4);
insert into user_preferences (user_id, cuisine_id) values (37, 1);
insert into user_preferences (user_id, cuisine_id) values (37, 3);
insert into user_preferences (user_id, cuisine_id) values (37, 8);
insert into user_preferences (user_id, cuisine_id) values (37, 2);
insert into user_preferences (user_id, cuisine_id) values (38, 7);
insert into user_preferences (user_id, cuisine_id) values (38, 6);
insert into user_preferences (user_id, cuisine_id) values (38, 4);
insert into user_preferences (user_id, cuisine_id) values (38, 5);
insert into user_preferences (user_id, cuisine_id) values (38, 1);
insert into user_preferences (user_id, cuisine_id) values (39, 8);
insert into user_preferences (user_id, cuisine_id) values (39, 1);
insert into user_preferences (user_id, cuisine_id) values (39, 2);
insert into user_preferences (user_id, cuisine_id) values (39, 5);
insert into user_preferences (user_id, cuisine_id) values (39, 3);
insert into user_preferences (user_id, cuisine_id) values (40, 9);
insert into user_preferences (user_id, cuisine_id) values (40, 8);
insert into user_preferences (user_id, cuisine_id) values (40, 6);
insert into user_preferences (user_id, cuisine_id) values (40, 5);
insert into user_preferences (user_id, cuisine_id) values (40, 3);
insert into user_preferences (user_id, cuisine_id) values (41, 4);
insert into user_preferences (user_id, cuisine_id) values (41, 7);
insert into user_preferences (user_id, cuisine_id) values (41, 1);
insert into user_preferences (user_id, cuisine_id) values (41, 9);
insert into user_preferences (user_id, cuisine_id) values (41, 8);
insert into user_preferences (user_id, cuisine_id) values (42, 3);
insert into user_preferences (user_id, cuisine_id) values (42, 4);
insert into user_preferences (user_id, cuisine_id) values (42, 6);
insert into user_preferences (user_id, cuisine_id) values (43, 4);
insert into user_preferences (user_id, cuisine_id) values (43, 3);
insert into user_preferences (user_id, cuisine_id) values (43, 1);
insert into user_preferences (user_id, cuisine_id) values (43, 6);
insert into user_preferences (user_id, cuisine_id) values (44, 2);
insert into user_preferences (user_id, cuisine_id) values (44, 8);
insert into user_preferences (user_id, cuisine_id) values (44, 9);
insert into user_preferences (user_id, cuisine_id) values (44, 3);
insert into user_preferences (user_id, cuisine_id) values (45, 1);
insert into user_preferences (user_id, cuisine_id) values (45, 5);
insert into user_preferences (user_id, cuisine_id) values (45, 3);
insert into user_preferences (user_id, cuisine_id) values (45, 2);
insert into user_preferences (user_id, cuisine_id) values (46, 2);
insert into user_preferences (user_id, cuisine_id) values (46, 3);
insert into user_preferences (user_id, cuisine_id) values (46, 9);
insert into user_preferences (user_id, cuisine_id) values (46, 6);
insert into user_preferences (user_id, cuisine_id) values (47, 9);
insert into user_preferences (user_id, cuisine_id) values (47, 6);
insert into user_preferences (user_id, cuisine_id) values (47, 8);
insert into user_preferences (user_id, cuisine_id) values (47, 3);
insert into user_preferences (user_id, cuisine_id) values (47, 1);
insert into user_preferences (user_id, cuisine_id) values (48, 7);
insert into user_preferences (user_id, cuisine_id) values (48, 9);
insert into user_preferences (user_id, cuisine_id) values (48, 2);
insert into user_preferences (user_id, cuisine_id) values (48, 3);
insert into user_preferences (user_id, cuisine_id) values (48, 1);
insert into user_preferences (user_id, cuisine_id) values (49, 8);
insert into user_preferences (user_id, cuisine_id) values (49, 7);
insert into user_preferences (user_id, cuisine_id) values (49, 3);
insert into user_preferences (user_id, cuisine_id) values (49, 4);
insert into user_preferences (user_id, cuisine_id) values (50, 6);
insert into user_preferences (user_id, cuisine_id) values (50, 3);
insert into user_preferences (user_id, cuisine_id) values (50, 2);
insert into user_preferences (user_id, cuisine_id) values (50, 1);

 










INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('La Tapería', 5, 3, 3, '1 Scotts Rd, #02 - 10 / 11, Singapore 228208', 67378336, '/lataperia.jpg', 'https://www.lataperia.com.sg/' );
INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('Esquina', 5, 4, 3, '16 Jiak Chuan Rd, Singapore 089267', 62221616,'/esquina.jpg', 'https://esquina.com.sg/');
INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('Baja Fresh', 5, 1, 1, '40 Woodlands Street 41, Level 2 High School Cafeteria, Singapore 738547', 34576812,'/download.jpeg', 'https://bajafresh.com.sg/');
INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('Guzman y Gomez - Northpoint City', 5, 1, 1, ' #01-176/177/178, 1 NorthPoint Dr, Northpoint City, 769019',  62544979,'/guzman.jpg', 'https://www.gyg.com.sg/');
INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('Rem.Inis', 5, 1, 1, '33 Sembawang Rd, Singapore 779084',  94882514,'/reminis.jpeg', 'https://m.facebook.com/rem.inis33/');
INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('Next Door Spanish Cafe', 5, 2, 2, '699 E Coast Rd, Singapore 459061',  81684009,'/nextdoorspanish.jpeg', 'https://www.nextdoorspanishcafe.com/');
INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('Lower East Side Tacqueria', 5, 3, 2, '19 E Coast Rd, Singapore 428746',   63481302,'/lowereastside.jpeg', 'https://www.facebook.com/lowereastside.sg/');
INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('Comida Mexicana Singapore', 5, 3, 2, '404 E Coast Rd, Singapore 428998
',   64408030,'/comida.jpeg', 'https://www.comidamex.com.sg/');
INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('Next Door Spanish Cafe', 5, 2, 2, '699 E Coast Rd, Singapore 459061',  81684009,'/nextdoorspanish.jpeg', 'https://www.nextdoorspanishcafe.com/');
INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('Los Jefes @ NEWest
', 5, 2, 4, '1 West Coast Drive, #01-73 NEWest Mall, W Coast Dr, 128020',   96529274,'/losjefes.jpg', 'https://www.facebook.com/losjefestacos');
INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('Cha Cha Cha Mexican Restaurant ', 5, 2, 4, 'Cha Cha Cha Mexican Restaurant', 64621650,'/cha-cha-cha.jpg', 'https://www.chachacha.com.sg/');
INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('My Little Spanish Place ', 5, 3, 4, ' 619 Bukit Timah Rd, Singapore 269720', 64632810, '/mylittlespanishplace.jpg', 'http://www.mylittlespanishplace.com.sg/');
INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('Tapas Club', 5, 2, 2, '78 Airport Blvd., #03 - 220 / 221 / 222, Singapore 819666', 66028081, 'https://www.tapasclub.com/');

INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('Himawari Japanese Restaurant', 1, 2, 1, '1 Orchid Club Rd #02-02/03, Driving Range unit (Carpark, A Orchid Country Club, 769162', 68343313, '/himawari.jpg', 'https://www.himawari.com.sg/');
INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('Kaiyo Sushi and Grill', 1, 2, 1, '13 Teck Chye Terrace, Singapore 545724', 69519203,'/kaiyo.jpg', 'https://www.facebook.com/kaiyosushigrill/');
INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('Sushi Express @ Sun Plaza', 1, 1, 1, '30 Sembawang Dr, #02-23, Singapore 757713',  62570937,'/sushiexpress.jpeg', 'http://www.sushiexpress.com.sg/');
INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('SUSHI TEI', 1, 2, 1, '930 Yishun Ave 2 #02-15, Northpoint City, 769098', 62572822,'/sushitei.jpg', 'https://sushitei.com/');
INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('Akimitsu', 1, 2, 1, '930 Yishun Ave 2, #02-28, Singapore 769098',  63339781,'/akimitsu.JPG', 'https://www.facebook.com/akimitsu.sg/');
INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('The Japanese Food Alley', 1, 1, 3, '73A Ayer Rajah Crescent, Singapore 139957', 92994877,'/jpnfoodalley.jpeg', 'https://www.facebook.com/thejapanesefoodalley/');
INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('Hakata Japanese Restaurant @ NeWest', 1, 2, 4, '1 W Coast Dr, #01-93/70 NEWest, Singapore 128020', 62654680, '/hakata.jpeg', 'https://www.hakatarestaurant.com/' );
INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('Momoya Japanese Restaurant Pte Ltd', 1, 3, 2, '16 Jln Pari Burong, Singapore 488682',  62453303, '/momoya.jpeg', 'https://www.facebook.com/MomoyaJapaneseRestaurant/' );
INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('Mikawa Yakitori Bar', 1, 2, 2, '81 Upper E Coast Rd, Singapore 455220',   64448484, '/mikawa.jpeg', 'https://www.facebook.com/MikawaYakitori/' );
INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('Iza Your Local Izakaya Bar', 1, 3, 2, '695 E Coast Rd, Singapore 459059', 63852883, '/iza.jpeg', 'https://www.facebook.com/iza.bar.siglap/' );
INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('Wahiro', 1, 3, 2, '50 East Coast Road #01-01 Roxy Square 1 Shopping Centre, 428769', 63422252, '/wahiro.jpeg', 'http://www.wahiro.com/' );
INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('Misaki', 1, 3, 3, '12 Marina Boulevard T3 #02-08, Tower 3, #02-08 Marina Bay Financial Centre, 018982', 64431187, '/misaki.jpeg', 'https://misakisg.com/' );
INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('Kiyoshi Japanese Restaurant', 1, 3, 3, '75 Amoy St, Singapore 069894', 62230995, '/kiyoshi.jpeg', 'https://kiyoshi.sg/' );
INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('Shinzo Japanese Cuisine', 1, 3, 3, '17 Carpenter St, Singapore 059906', 64382921, '/shinzo.jpeg', 'https://www.shinzo.com.sg/' );
INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('Kotobuki', 1, 2, 4, '3 Yuan Ching Rd, #01-02A, Singapore 618642', 62612272, '/kotobuki.jpeg', 'http://www.sapporo.com.sg/our-restaurants' );
INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('Isuramuya Japanese Restaurant & Marketplace
', 1, 3, 4, '2 Jurong East Central 1, #04-19 JCube, Singapore 609731', 62623008, '/isuramuya.jpeg', 'https://www.isuramuya.com/' );
INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('Takagi Ramen - Jurong West', 1, 2, 4, 'Jurong West Street 41, #01-74 Block 492, Singapore 640492', 6962519, '/takagi.jpeg', 'https://takagiramen.com/' );

INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('Guiga Korean BBQ Restaurant', 2, 3, 3, '134 Tg Pagar Rd, Singapore 088538', 62213001, '/guiga.jpeg', 'https://m.facebook.com/guigakoreanbbq/' );select * 
INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('Hongdae Korean Restaurant', 2, 2, 3, '118 Neil Rd, Singapore 088854', 64388907, '/hongdae.jpeg', 'https://www.facebook.com/hongdaekoreanbbq/' );
INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('Seoul Restaurant', 2, 3, 3, 'Regent Singapore #03-02, 1 Cuscaden Rd, 249715', 6962519, '/takagi.jpeg', 'https://takagiramen.com/' );
INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('Seoul Kitchen', 2, 3, 1, '435 Sembawang Rd, Singapore 758398',  64830818, '/seoulkitchen.jpeg', 'https://www.facebook.com/SeoulKitchenSG' );
INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('Seoul Garden HotPot Northpoint City', 2, 3, 1, '930 Yishun Ave 2, #03-06 Northpoint City North Wing, Singapore 769098', 62575339, '/seoulgarden.jpeg', 'http://seoulgardenhotpot.com.sg/outlets/' );
INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('Jangsu Korean BBQ', 2, 2, 2, '19 Teck Chye Terrace, Singapore 545725', 62894104, '/jangsu.jpeg', 'https://jangsu-korean-bbq.business.site/?utm_source=gmb&utm_medium=referral' );
INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('HoHo Chimek', 2, 2, 2, '430 Upper Changi Rd, #01-45, Singapore 487048', 67332828, '/hohochimek.jpeg', 'https://www.hohochimek.com/' );
INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('Paiks Bibim @ Bedok Mall', 2, 2, 2, '311 New Upper Changi Rd, #01-95, Singapore 467360', 68449628, '/paikbibim.jpeg', 'https://www.facebook.com/paiks.bibimsg/' );
INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('Muk-Bang Korean Restaurant', 2, 2, 2, 'ESR BizPark @Chai Chee (Formerly Viva Business Park)', 66046328, '/mukbang.jpeg', 'https://www.facebook.com/mukbang.official/' );
INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('AHTTI Korean Restaurant', 2, 2, 4, '2 Venture Dr, #02-43 Vision Exchange, Singapore 608526', 68039341, '/ahtti.jpeg', 'https://www.facebook.com/ahttikr/' );
INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('Nipong Naepong JEM', 2, 2, 4, '50 Jurong Gateway Rd, #01-16 Jem, Singapore 608549', 68168061, '/nipong.jpeg', 'https://www.facebook.com/nipongnaepongsingapore/' );
INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('Woorinara Korean Restaurant', 2, 3, 4, '19 Lor Kilat, #01-02, Singapore 598120', 64649282, '/woorina.jpeg', 'https://woorinara.sg/' );
INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('Sunny Korean Cuisine', 2, 1, 4, '154 West Coast Rd, Singapore 127371', 96547210, '/sunnykorean.jpeg', 'https://www.ladyironchef.com/2017/05/sunny-korean-cuisine/' );
INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('Bigmama Korean Restaurant', 2, 3, 3, '2 Kim Tian Rd, Singapore 169244', 62707704, '/bigmama.jpeg', 'https://takeaway.bigmama.sg/' );

INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('Coba Coba', 3, 2, 1, '156 Yishun Street 11, #01-106, Singapore 760156', 63822622, '/cobacoba.jpeg', 'https://www.cobacoba.sg/' );
INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('Malaysia Chiak!', 3, 1, 1, '930 Yishun Avenue 2, #B1-194/195/203/204, 205, 769098', 63701155, '/malaysia.jpeg', 'https://feisionggroup.com.sg/index.php/our-brands/malaysia-chiak' );
INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('Rasa Istimewa Waterfront Restaurant', 3, 3, 1, '6A Admiralty Rd W, Singapore 757445', 63669339, '/rasaistimewa.jpeg', 'https://www.rasaistimewa.sg/' );
INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('Ahmad Power Cuisine (Nasi Ayam Penyet)', 3, 1, 1, '292 Yishun Street 22, 01-275, Singapore 760292', 91624396, '/ahmad.jpeg', 'https://www.instagram.com/ahmadpowercuisine/' );
INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('Malaysia Local Delights', 3, 2, 2, '224 Tanjong Katong Rd, Singapore 437015', 64408378, '/msialocal.jpeg', 'https://sethlui.com/malaysia-local-delights-singapore/' );
INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('Spize Bedok', 3, 2, 2, '336 Bedok Road, Bedok Shopping Complex, 469512', 63377493, '/spize.jpeg', 'https://spize.sg/' );
INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('Hjh Maimunah Restaurant & Catering Pte Ltd', 3, 2, 2, '20 Joo Chiat Rd, Singapore 427357, 469512', 63485457, '/hjh.jpeg', 'http://www.hjmaimunah.com/' );
INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('Cucu Raimah Malay Food', 3, 1, 2, '56 Jln Kembangan, Raimah Eating House, Singapore 419120', 63377493, '/cucu.jpeg', 'https://www.facebook.com/cucuraimahMF/' );
INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('Pu3 Restaurant', 3, 2, 3, '111 Somerset Rd, #02-20 TripleOne Somerset, Singapore 238164', 92720034, '/pu3.jpeg', 'https://www.facebook.com/pu3restaurant/' );
INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('Cumi Bali Indonesian Restaurant', 3, 3, 3, '50 Tras St, Singapore 078989', 62206619, '/cumibali.jpeg', 'https://www.cumibali.com/' );
INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('Bara', 3, 2, 3, '16 Enggor St, 01-10, Singapore 079717', 81826876, '/bara.jpeg', 'https://www.bara-food.com/' );
INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('IndoChili', 3, 2, 3, '54 Zion Rd, Singapore 247779
', 64451766, '/indochili.jpeg', 'https://www.indochili.com/' );
INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('Gado & Grill @ One Raffles Place', 3, 2, 3, '1 Raffles Place, #B1-20, Singapore 048616',  64521182, '/gado.jpeg', 'https://gadogrill.com/' );
INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('Bebek Goreng Pak Ndut @Westgate', 3, 2, 4, '3 Gateway Dr, #B1-11 Westgate, Singapore 608532',  65654787, '/bebek.jpeg', 'https://bebekgorengpakndut.com.sg/' );
INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('Ayam Penyet Ria', 3, 2, 4, '1 Jurong West Central 2, JP1, #B1-06, Singapore 648886', 67943015, '/ayampenyet.jpeg', 'https://ayampenyetria.com/' );

INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('Tasty Loong at Orto Park', 4, 3, 1, '81 Lor Chencharu, Singapore 769198', 94726210, '/orto.jpeg', 'https://www.tastyloong.com/' );
INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('Pin Si Restaurant', 4, 3, 1, '60 Yishun Ave 4, #02-01 Safra Country Club', 68528933, '/pinsi.jpeg', 'https://pinsi.com.sg/' );
INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('The Famous Kitchen', 4, 3, 1, '54 Sembawang Road Hong Heng Mansions, 779085', 62571843, '/famouskitchen.jpeg', 'https://www.famouskitchen.com.sg/' );
INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('PUTIEN', 4, 3, 1, '930 Yishun Ave 2, Northpoint Shopping Centre, 02-42/43/44, 769098', 62571482, '/putein.jpeg', 'https://www.putien.com/' );
INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('Jia Wei Chinese Restaurant', 4, 2, 2, '50 East Coast Road, Roxy Square, Level 2 Grand Mercure Singapore Roxy, 428769', 63405678, '/jiawei.jpeg', 'https://www.grandmercureroxy.com.sg/dining/jia-wei-chinese-restaurant' );
INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('Sin Hoi Sai Eating House', 4, 2, 2, '187 E Coast Rd, Singapore 428893', 64406956, '/sinhoisai.jpeg', 'https://sinhoisai.ezqr.sg/' );
INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('Goldleaf Restaurant', 4, 3, 2, '88 E Coast Rd, #01-05/06/07 Katong Square, Singapore 423371', 63461088, '/goldleaf.jpeg', 'https://goldleaf.com.sg/' );
INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('North South Cuisine', 4, 2, 3, '351 Beach Rd, Singapore 199571', 62993197, '/northsouth.jpeg', 'https://m.facebook.com/profile.php?id=216874228346287&__tn__=%2As-R' );
INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('Hua Ting Restaurant', 4, 4, 3, 'Orchard Hotel Singapore, Level 2, 442 Orchard Rd, 238879', 63461088, '/huating.jpeg', 'https://www.millenniumhotels.com/en/singapore/orchard-hotel-singapore/hua-ting-restaurant/' );
INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('Summer Pavilion', 4, 4, 3, '7 Raffles Ave, Singapore 039799', 64345286, '/summerpavillion.jpeg', 'https://www.ritzcarlton.com/en/hotels/singapore/dining/summer-pavilion' );
INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('Jade', 4, 3, 3, ' 1 Fullerton Square, Singapore 049178', 68778188, '/jade.jpeg', 'https://www.fullertonhotels.com/fullerton-hotel-singapore/dining/restaurants-and-bars/jade' );
INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('Lotus Garden Restaurant', 4, 3, 4, ' 1 West Coast Drive, #01-78 NEWest, W Coast Dr, Singapore 128020', 62653718, '/lotusgarden.jpeg', 'http://lotusgarden.com.sg/' );
INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('Crystal Jade Hong Kong Kitchen', 4, 2, 4, ' 3155 Commonwealth Ave W, #03-54 The Clementi Mall, Singapore 129588',  6659 9215, '/crystaljade.jpeg', 'https://www.crystaljade.com/' );
INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('Chin Huat Live Seafood', 4, 2, 4, ' Clementi Street 12, #01-30 Block 105, Singapore 120105', 67757348, '/chinhuat.jpeg', 'http://chinhuatliveseafood.sg/' );

INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('COLLINS® @ Westgate', 6, 2, 4, '3 Gateway Drive, Mall, #01-05 Westgate, 608532', 62567863, '/collins.jpeg', 'https://www.collins.sg/' );
INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('The Carving Board', 6, 3, 4, ' 252 Jurong East Street 24, #01-107, Singapore 600252', 97898262, '/carvingboard.jpeg', 'https://thecarvingboard.oddle.me/en_SG/' );
INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('Brotzeit Westgate', 6, 3, 4, ' 3 Gateway Dr, #01-04, Singapore 608532', 64659874, '/brozeit.jpeg', 'https://brotzeit.co/' );
INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('The Little Grill', 6, 2, 4, ' 215 Jurong East Street 21, Block 215, Singapore 600215', 97898262, '/littlegrill.jpeg', 'https://www.facebook.com/thelittlegrillsingapore/' );
INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('Lawrys The Prime Rib Singapore', 6, 4, 3, '333A Orchard Rd, #04-01/31, Singapore 238897',   68363333, '/lawrys.jpeg', 'http://www.lawrys.com.sg/' );
INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('Southwest Tavern', 6, 2, 3, '8 Boon Lay Way, Singapore 609964', 65154303, '/southwest.jpg', 'https://www.facebook.com/swtavern/' );
INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('Buddy Hoagies Steak & Grill Restaurant (East Point)', 6, 3, 2, '3 Simei Street 6, #02-06 East Point, Singapore 528833', 69574810, '/buddy.jpeg', 'http://www.buddyhoagies.com.sg/' );
INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('Tokyo Western Food', 6, 2, 2, '823A Tampines Street 81, Singapore 521823', 93513077, '/tokyowest.jpeg', 'https://www.burpple.com/tokyo-western-food' );
INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('Smokin Joe - Western BBQ Charcoal Grill', 6, 2, 1, 'Yishun Park Hawker Centre #01-37, 51 Yishun Ave 11, 768867', 90065004, '/smokinjoe.jpeg', 'http://www.smokinjoe.com.sg/' );
INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('COLLINS® @ Northpoint City', 6, 2, 1, '930 Yishun Ave 2, #01-113/114 NORTHPOINT, Singapore 769098', 64819036, '/collinsnorth.jpeg', 'https://www.collins.sg/' );

INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('La Pizzaiola @ Kalidasa', 7, 2, 1, '19 Kalidasa Ave, Singapore 789398', 64554648, '/pizzaiola.jpeg', 'http://www.lapizzaiola.com.sg/' );
INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('Pietro Ristorante Italiano', 7, 3, 1, '12 Jln Kelulut, Singapore 809030', 64845528, '/pietro.jpeg', 'http://pietro.com.sg/' );
INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('Al Forno (East Coast) Pte Ltd', 7, 3, 2, '400 E Coast Rd, Singapore 428996', 63488781, '/alforno.jpeg', 'http://alfornoeastcoast.com.sg/' );
INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('Pasta Fresca Da Salvatore (Siglap)', 7, 3, 2, '9 Upper East Coast Rd, #01-01, Singapore 455203
', 62415560, '/pastafresca.jpeg', 'https://www.pastafresca.com/outlet/pasta-fresca-east-coast/' );
INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('Pietrasanta The Italian Restaurant', 7, 3, 3, '1 Fusionopolis Way, #01-08, Singapore 138632
', 98639253, '/pietrasanta.jpeg', 'http://www.ristorante-pietrasanta.com/' );
INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('Morettino', 7, 3, 3, '100 Tras St, #01 - 04, Singapore 079027
', 62440424, '/morettino.jpeg', 'https://www.morettinocafe.com/' );
INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('Brio', 7, 3, 4, '1 Jurong West Central 2, #02-24/K5 Jurong Point, Singapore 648886
', 67959606, '/brio.jpeg', 'https://brio.com.sg/' );
INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('iO Italian Osteria Singapore', 7, 3, 4, '4 Hillview Rise, #02-01, Singapore 667979
', 67107150, '/io.jpeg', 'https://io-osteria.com/' );

INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('Syed Restaurant', 8, 2, 1, '292, 01-301 Yishun Street 22, 760292
', 65554998, '/syed.jpeg', 'http://syed-restaurant.ezpage.me/#gsc.tab=0' );
INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('Shami Banana Leaf', 8, 2, 1, '349 Sembawang Rd, Singapore 758356
', 67543898, '/shami.jpeg', 'https://m.facebook.com/pages/Shami-Banana-Leaf-Delights/204574439557426' );
INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('Royal Taj @ Village Hotel', 8, 3, 2, ' 2, block 16 Gunner Ln, 02-06 Singapore Mess Hall, 099567
', 91185896, '/royaltaj.jpeg', 'https://www.royaltaj.sg/' );
INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('Zaffron Kitchen East Coast', 8, 3, 2, '137 E Coast Rd, 135, Singapore 428820
', 64406786, '/zaffron.jpeg', 'https://www.zaffronkitchen.com/' );
INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('Spice Grill Restaurant', 8, 3, 3, 'Spice Grill Restaurant
', 62222921, '/spicegrill.jpeg', 'https://spicegrill.sg/' );
INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('Curry Village', 8, 3, 3, '8 Lim Teck Kim Rd, Singapore 088937
', 62214222, '/curryv.jpeg', 'https://www.facebook.com/Curryvilllage/' );
INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('Khansama Tandoori Village', 8, 3, 4, '87 Science Park Dr, Singapore 118260
', 67760300, '/khansama.jpeg', ' https://khansama.com.sg/?SID=jn47vamfvsaecmu3nf32hbav95' );
INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('Anjana Kitchen - Best Indian Restaurant Singapore', 8, 3, 4, '​2, Venture Dr, Vision Exchange, 608526
', 62531959, '/anjana.jpeg', 'http://www.anjanakitchen.com/' );

INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('Nong Nying Thai Kitchen', 9, 2, 1, '​Nong Nying Thai Kitchen
', 84391189, '/nongnying.jpeg', 'https://www.facebook.com/ThaiKitchenWoodland/' );
INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('Phuket Thai Kitchen', 9, 2, 1, '​1018 Sembawang Rd, Singapore 758495
', 83822443, '/ phuketthai.jpeg', 'https://phuket-thai-kitchen.business.site/?utm_source=gmb&utm_medium=referral' );
INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('Central Thai - East Coast Park', 9, 2, 2, '1300 East Coast Parkway, East Coast Park Area F, 468964
', 64435510
, '/centralthai.jpeg', 'https://www.centralthai.com.sg/' );
INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('Kinnari Thai Cuisine', 9, 3, 2, '201 Joo Chiat Rd, #01-01, Singapore 427472
', 93282928, '/kinnari.jpeg', 'https://www.kinnarithai.com/' );
INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('Galamang Thai', 9, 2, 3, '​Jalan Bukit Merah, #01-5134 Block 2, Singapore 150002
', 91141505, '/galamang.jpeg', 'https://www.burpple.com/f/DavVxLmq' );
INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('Rattana Thai Restaurant', 9, 2, 3, '​1 Tanjong Pagar Plaza, #02-30, Singapore 082001
', 62244322, '/rattana.jpeg', 'http://rattanathairestaurant.com.sg/' );
INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('Soi Thai Kitchen - Jurong West', 9, 2, 4, '​Jurong West Ave 1, #01-811 Block 502, Singapore 640502
', 62661811, '/soithai.jpeg', 'https://soi-thai-kitchen-jurong-west.business.site/' );
INSERT INTO restaurants (name, cuisine_id, budget_id, location_id, address, phone_number, photo, website) VALUES ('Nakhon Kitchen - Kovan', 9, 3, 4, '​212 Hougang Street 21, #01-341, Singapore 530212
', 62868785, '/nakhon.jpeg', 'https://nakhongroup.com/nakhonkitchen/' );














